#!/bin/csh

# **********************
# PIPE
# **********************

## - STEP 9 -
## Proceed to follow-on pipe script if it exists

if (-e $script_dir/$runon_script_name) then
	source $script_dir/$runon_script_name
else 
	echo "Follow on script not written."
	echo
	goto error
endif

## - STEP 10 -
## Proceed to post pipe script

source $script_dir/post_pipe

error:
exit 1

