#!/bin/csh

##################################
# L2_setup 			 #
# Last Modified Date:   21/02/11 #
##################################

######################
# set up environment #
######################

setenv L2_BASE_DIR `locate frodo_l2_pipeline/trunk | head -1`	# AUTO
# setenv L2_BASE_DIR "/home/rmb/frodo_l2_pipeline/trunk"	# MANUAL:laptop

setenv L2_BIN_DIR $L2_BASE_DIR/bin
setenv L2_LIB_DIR $L2_BASE_DIR/lib
setenv L2_CONFIG_DIR $L2_BASE_DIR/config
setenv L2_SRC_DIR $L2_BASE_DIR/src
setenv L2_SCRIPT_DIR $L2_BASE_DIR/scripts
setenv L2_MAN_DIR $L2_BASE_DIR/man

setenv L2_ERROR_CODES_FILE $L2_CONFIG_DIR/ERROR_CODES

setenv L2_HEADER_FILE $L2_MAN_DIR/HEADER
setenv L2_FRFS_BLURB_FILE $L2_MAN_DIR/FRODO_RED_FINDPEAKS_SIMPLE
setenv L2_FRFSC_BLURB_FILE $L2_MAN_DIR/FRODO_RED_FINDPEAKS_SIMPLE_CLEAN
setenv L2_FRT_BLURB_FILE $L2_MAN_DIR/FRODO_RED_TRACE
setenv L2_FRES_BLURB_FILE $L2_MAN_DIR/FRODO_RED_EXTRACT_SIMPLE
setenv L2_FRA_BLURB_FILE $L2_MAN_DIR/FRODO_RED_ARCFIT
setenv L2_FRCT_BLURB_FILE $L2_MAN_DIR/FRODO_RED_CORRECT_THROUGHPUT

setenv L2_VERSION_FILE $L2_MAN_DIR/VERSION

################
# set up shell #
################

limit stacksize unlimited

################
# core aliases #
################

alias frfind $L2_BIN_DIR/frfind
alias frclean $L2_BIN_DIR/frclean
alias frtrace $L2_BIN_DIR/frtrace
alias frextract $L2_BIN_DIR/frextract
alias frarcfit $L2_BIN_DIR/frarcfit
alias frcorrect $L2_BIN_DIR/frcorrect

alias modhead $L2_BIN_DIR/modhead
alias imcopy $L2_BIN_DIR/imcopy

##################
# script aliases #
##################

alias l2rfr $L2_SCRIPT_DIR/L2_calib_reduce-focus-run

###########################
# update man/VERSION file #
###########################

set author = `svn info $L2_BASE_DIR | grep "Last Changed Author" | awk -F "Author:" '{print $2}'`
set rev = `svn info $L2_BASE_DIR | grep "Last Changed Rev" | awk -F "Rev:" '{print $2}'`
set date = `svn info $L2_BASE_DIR | grep "Last Changed Date" | awk -F "Date:" '{print $2}'`

set author = "Last Changed Author:\t$author"
set rev = "Last Changed Revision:\t$rev"
set date = "Last Changed Date:\t$date"

echo $author > $L2_VERSION_FILE
echo $rev >> $L2_VERSION_FILE	
echo $date >> $L2_VERSION_FILE

