#!/bin/csh

##################################
# L2_update_version		 #
# Last Modified Date:   26/01/11 #
##################################

set author = `svn info $L2_BASE_DIR | grep "Last Changed Author" | awk -F "Author:" '{print $2}'`
set rev = `svn info $L2_BASE_DIR | grep "Last Changed Rev" | awk -F "Rev:" '{print $2}'`
set date = `svn info $L2_BASE_DIR | grep "Last Changed Date" | awk -F "Date:" '{print $2}'`

set author = "Last Changed Author:\t$author"
set rev = "Last Changed Revision:\t$rev"
set date = "Last Changed Date:\t$date"

echo $author > $L2_VERSION_FILE
echo $rev >> $L2_VERSION_FILE	
echo $date >> $L2_VERSION_FILE


